version: '3'
services:
  mssql_server:
    container_name: sqlserver2019_Express
    hostname: sqlserver2019_Express
    ports:
      - "1433:1433"
    network_mode: "bridge"
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=saPassword1234
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
    volumes:
      - "./mssqlserver/data:/var/opt/mssql/data"
      - "./mssqlserver/log:/var/opt/mssql/log"
      - "./mssqlserver/secrets:/var/opt/mssql/secrets"
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: 
      - "./ftpd/data:/home/username/"
      - "./ftpd/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/ftpusers/username
    restart: always
